/*
 * Copyright (c) 2022-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* 错误码定义（自 cm_type.h 拆出以控制单头行数；cm_type.h 继续透出本头，
 * 既有 include 路径与取值不变，二进制/源码兼容）。新增错误码先查分段
 * （-10000~-19999 非法参数段 / -20000~-29999 密钥操作段 / -30000~-39999
 * 授权段；CMR_DIALOG_ERROR_* 为弹框专用段，不参与 ConvertErrorCode 折叠）。 */

#ifndef CM_ERROR_CODE_H
#define CM_ERROR_CODE_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum CmErrorCode {
    CM_SUCCESS = 0,
    CM_FAILURE = -1,

    CMR_ERROR_NOT_PERMITTED = -2,
    CMR_ERROR_NOT_SUPPORTED = -3,
    CMR_ERROR_STORAGE = -4,
    CMR_ERROR_NOT_FOUND = -5,
    CMR_ERROR_NULL_POINTER = -6,
    CMR_ERROR_INVALID_ARGUMENT = -7,
    CMR_ERROR_MAKE_DIR_FAIL = -8,
    CMR_ERROR_INVALID_OPERATION = -9,
    CMR_ERROR_OPEN_FILE_FAIL = -10,
    CMR_ERROR_READ_FILE_ERROR = -11,
    CMR_ERROR_WRITE_FILE_FAIL = -12,
    CMR_ERROR_REMOVE_FILE_FAIL = -13,
    CMR_ERROR_CLOSE_FILE_FAIL = -14,
    CMR_ERROR_MALLOC_FAIL = -15,
    CMR_ERROR_NOT_EXIST = -16,
    CMR_ERROR_ALREADY_EXISTS = -17,
    CMR_ERROR_INSUFFICIENT_DATA = -18,
    CMR_ERROR_BUFFER_TOO_SMALL = -19,
    CMR_ERROR_INVALID_CERT_FORMAT = -20,
    CMR_ERROR_PARAM_NOT_EXIST = -21,
    CMR_ERROR_SESSION_REACHED_LIMIT = -22,
    CMR_ERROR_PERMISSION_DENIED = -23,
    CMR_ERROR_AUTH_CHECK_FAILED = -24,
    CMR_ERROR_KEY_OPERATION_FAILED = -25,
    CMR_ERROR_NOT_SYSTEMP_APP = -26,
    CMR_ERROR_MAX_CERT_COUNT_REACHED = -27,
    CMR_ERROR_ALIAS_LENGTH_REACHED_LIMIT = -28,
    CMR_ERROR_GET_ADVSECMODE_PARAM_FAIL = -29,
    CMR_ERROR_DEVICE_ENTER_ADVSECMODE = -30,
    CMR_ERROR_CREATE_RDB_TABLE_FAIL = -31,
    CMR_ERROR_INSERT_RDB_DATA_FAIL = -32,
    CMR_ERROR_UPDATE_RDB_DATA_FAIL = -33,
    CMR_ERROR_DELETE_RDB_DATA_FAIL = -34,
    CMR_ERROR_QUERY_RDB_DATA_FAIL = -35,
    CMR_ERROR_PASSWORD_IS_ERR = -36,

    CMR_ERROR_OPENSSL_FAIL = -37,
    CMR_ERROR_MAX_GRANT_COUNT_REACHED = -38,
    CMR_ERROR_SA_START_STATUS_INIT_FAILED = -39,
    CMR_ERROR_SA_START_HUKS_INIT_FAILED = -40,
    CMR_ERROR_SA_START_PUBLISH_FAILED = -41,
    CMR_ERROR_IPC_PARAM_SIZE_INVALID = -42,
    CMR_ERROR_GET_LOCAL_TIME_FAILED = -43,
    CMR_ERROR_MEM_OPERATION_COPY = -44,
    CMR_ERROR_MEM_OPERATION_PRINT = -45,
    CMR_ERROR_FILE_OPEN_DIR = -46,
    CMR_ERROR_FILE_STAT = -47,
    CMR_ERROR_CERT_COUNT_MISMATCH = -48,
    CMR_ERROR_GET_CERT_STATUS = -49,
    CMR_ERROR_GET_CERT_SUBJECT_ITEM = -50,
    /* ukey failed */
    CMR_ERROR_UKEY_GENERAL_ERROR = -51,
    CMR_ERROR_UKEY_DEVICE_SUPPORT = -52,
    CMR_ERROR_HUKS_GENERAL_ERROR = -53,
    CMR_ERROR_VERIFY_PARAM_ERROR = -54,

    CMR_ERROR_IPC_WRITE_FAIL = -55,

    /* invalid argument */
    CMR_ERROR_INVALID_ARGUMENT_BEGIN = -10000,
    CMR_ERROR_INVALID_PARAMSET_ARG = -10001,
    CMR_ERROR_INVALID_ARGUMENT_STORE_TYPE = -10002,
    CMR_ERROR_INVALID_ARGUMENT_SCOPE = -10003,
    CMR_ERROR_INVALID_ARGUMENT_USER_ID = -10004,
    CMR_ERROR_INVALID_ARGUMENT_UID = -10005,
    CMR_ERROR_INVALID_ARGUMENT_URI = -10006,
    CMR_ERROR_INVALID_ARGUMENT_STATUS = -10007,
    CMR_ERROR_INVALID_ARGUMENT_APP_CERT = -10008,
    CMR_ERROR_INVALID_ARGUMENT_APP_PWD = -10009,
    CMR_ERROR_INVALID_ARGUMENT_ALIAS = -10010,
    CMR_ERROR_INVALID_ARGUMENT_SIGN_SPEC = -10011,
    CMR_ERROR_INVALID_ARGUMENT_HANDLE = -10012,
    CMR_ERROR_INVALID_ARGUMENT_CRED_PREVKEY = -10013,
    CMR_ERROR_STORE_PATH_NOT_SUPPORTED = -10014,
    CMR_ERROR_INVALID_ARGUMENT_LENGTH_ZERO = -10015,
    CMR_ERROR_INVALID_ARGUMENT_LENGTH_TOO_LARGE = -10016,
    CMR_ERROR_INVALID_ARGUMENT_END = -19999,

    /* key operation failed */
    CMR_ERROR_KEY_OPERATION_BEGIN = -20000,
    CMR_ERROR_KEY_IMPORT_PARAM_FAILED = -20001,
    CMR_ERROR_KEY_IMPORT_FAILED = -20002,
    CMR_ERROR_KEY_DELETE_PARAM_FAILED = -20003,
    CMR_ERROR_KEY_DELETE_FAILED = -20004,
    CMR_ERROR_KEY_MAC_PARAM_FAILED = -20005,
    CMR_ERROR_KEY_MAC_INIT_FAILED = -20006,
    CMR_ERROR_KEY_MAC_FINISH_FAILED = -20007,
    CMR_ERROR_KEY_GENERATE_PARAM_FAILED = -20008,
    CMR_ERROR_KEY_GENERATE_FAILED = -20009,
    CMR_ERROR_KEY_INIT_PARAM_FAILED = -20010,
    CMR_ERROR_KEY_INIT_FAILED = -20011,
    CMR_ERROR_KEY_PROCESS_PARAM_FAILED = -20012,
    CMR_ERROR_KEY_UPDATE_FAILED = -20013,
    CMR_ERROR_KEY_FINISH_FAILED = -20014,
    CMR_ERROR_KEY_ABORT_FAILED = -20015,
    CMR_ERROR_KEY_CHECK_EXIST_PARAM_FAILED = -20016,
    CMR_ERROR_KEY_CHECK_EXIST_FAILED = -20017,
    CMR_ERROR_KEY_OPERATION_END = -29999,

    /* auth check failed */
    CMR_ERROR_AUTH_FAILED_BEGIN = -30000,
    CMR_ERROR_AUTH_FAILED_MAC_FAILED = -30001,
    CMR_ERROR_AUTH_FAILED_MAC_MISMATCH = -30002,
    CMR_ERROR_AUTH_FAILED_END = -39999,
};

enum CMDialogErrorCode {
    CMR_DIALOG_ERROR_INSTALL_FAILED = -5,

    CMR_DIALOG_ERROR_INTERNAL = -1000,
    CMR_DIALOG_ERROR_OPERATION_CANCELS = -1001,
    CMR_DIALOG_ERROR_PARSE_CERT_FAILED = -1002,
    CMR_DIALOG_ERROR_NOT_ENTERPRISE_DEVICE = -1003,
    CMR_DIALOG_ERROR_ADVANCED_SECURITY = -1004,
    CMR_DIALOG_ERROR_INCORRECT_FORMAT = -1005,
    CMR_DIALOG_ERROR_MAX_QUANTITY_REACHED = -1006,
    CMR_DIALOG_ERROR_SA_INTERNAL_ERROR = -1007,
    CMR_DIALOG_ERROR_NOT_EXIST = -1008,
    CMR_DIALOG_ERROR_NOT_SUPPORTED = -1009,
    CMR_DIALOG_ERROR_PARAM_INVALID = -1010,
    CMR_DIALOG_ERROR_PERMISSION_DENIED = -1011, /* UIExtension will return -1011 if permission check failed */
    CMR_DIALOG_ERROR_CAPABILITY_NOT_SUPPORTED = -1012, /* UIExtension will return -1012 if device check failed */
    CMR_DIALOG_ERROR_NO_AVAILABLE_CERTIFICATE = -1013, /* UIExtension will return -1013 if no available cert to use*/
    CMR_DIALOG_ERROR_PARAMETER_VALIDATION_FAILED = -1014,
    CMR_DIALOG_ERROR_START_UIABILITY_FAILED = -1015,
    CMR_DIALOG_ERROR_UKEY_REPORT_TIMEOUT = -1017, /* provider did not report result within total timeout */
    CMR_DIALOG_ERROR_UKEY_DIALOG_IN_PROGRESS = -1018, /* another ukey pin dialog session is in progress */
    CMR_DIALOG_ERROR_NOT_REGISTERED = -1019, /* 未注册驱动弹框，或 ForDriver 指定扩展不存在/类型不符（→29700003） */
    CMR_DIALOG_ERROR_NOT_PC_DEVICE = -1020, /* UIExtension dialog requires a PC device or PC mode (29700005) */

    CMR_DIALOG_ERROR_UIABILITY_NOT_SUPPORTED = -1021, /* ukey driver pin dialog is a UIAbility, rejected (29700003) */
};

#ifdef __cplusplus
}
#endif

#endif /* CM_ERROR_CODE_H */
