# Copyright (c) 2025-2026 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//base/security/certificate_manager/cert_manager.gni")
import("//build/ohos.gni")

config("cm_metrics_config") {
  include_dirs = [ "include" ]
}

ohos_static_library("libcm_metrics_static") {
  branch_protector_ret = "pac_ret"
  sanitize = {
    boundary_sanitize = true
    cfi = true
    cfi_cross_dso = true
    debug = false
    integer_overflow = true
    ubsan = true
    stack_protector_ret = true
  }

  include_dirs = [ "include" ]

  public_configs = [
    ":cm_metrics_config"
  ]

  sources = [ "src/cm_metrics.cpp" ]

  external_deps = [
    "hilog:libhilog"
  ]

  cflags_cc = [
    "-Wall",
    "-Werror",
  ]

  if (cm_api_metrics_enable) {
    cflags_cc += [ "-DCM_API_METRICS_ENABLE" ]
    external_deps += [ "api_metrics:histogrammanager" ]
  }

  part_name = "certificate_manager"
  subsystem_name = "security"
}
